#!/usr/bin/env bash
#
# @(#) dfu-flash-elf
#
# This script flashes ELF firmware to an STM32 device over USB in
# bootloader DFU Mode.
#
# The following values are defaults and can be changed by setting the
# corresponding environment variable.
#
#     ENVIRONMENT VARIABLE               DEFAULT VALUE
#     ====================               =============
#     BOOTLOADER_VID                     0x0483
#     BOOTLOADER_PID                     0xDF11
#     TEXT_ADDRESS                       0x08000000
#
: ${ARM_NONE_OBJCOPY_CMD:='/usr/bin/arm-none-eabi-objcopy'}
: ${BIN2DFU_CMD:="${HOME}/bin/bin2dfu"}
: ${CAT_CMD:='/bin/cat'}
: ${DFU_UTIL_CMD:='/usr/bin/dfu-util'}
: ${FILE_CMD:='/usr/bin/file'}
: ${GREP_CMD:='/bin/grep'}
: ${LS_CMD:='/bin/ls'}
: ${LSUSB_CMD:='/usr/bin/lsusb'}
: ${READLINK_CMD:='/usr/bin/readlink'}
: ${RM_CMD:='/bin/rm'}

# Default VID, PID and firmware flash memory address for STM32 MCU
: ${BOOTLOADER_VID:='0x0483'}
: ${BOOTLOADER_PID:='0xDF11'}
: ${TEXT_ADDRESS:='0x08000000'}

usage ()
{
    $CAT_CMD >&2 <<EOF
$1
Usage: ${script_name} ELF-FILE
EOF
}

# More OS-agnstoic readlink for existent files/directories.
resolve-existing ()
{
    case $($READLINK_CMD --version 2>&1) in
        *coreutils*)
            $READLINK_CMD -e "$@" || return $?
            ;;
        *)
            $READLINK_CMD -f N "$@" || return $?
            ;;
    esac
}

validate-elf ()
{
    local firmware_elf=$1

    local status=''

    case $($FILE_CMD "$firmware_elf") in
        *'ELF 32-bit LSB'*) status=0 ;;
        *) status=1 ;;
    esac

    return $status
}

generate-bin ()
{
    local firmware_elf=$1

    local firmware_bin=${firmware_elf%.elf}.bin

    $ARM_NONE_OBJCOPY_CMD -O binary "$firmware_elf" "$firmware_bin" || return $?
    echo "$firmware_bin"
}

generate-dfu ()
{
    local firmware_bin=$1

    local firmware_dfu=${firmware_bin%.bin}.dfu

    $BIN2DFU_CMD -D "${BOOTLOADER_VID}:${BOOTLOADER_PID}" \
                   -b "${TEXT_ADDRESS}:${firmware_bin}" \
                   "$firmware_dfu" || return $?
    echo "$firmware_dfu"
}

flash-dfu ()
{
    local firmware_dfu=$1

    if $LSUSB_CMD | $GREP_CMD -q 'DFU Mode'; then
        $DFU_UTIL_CMD -a 0 -d "${BOOTLOADER_VID}:${BOOTLOADER_PID}" \
                      -D "$firmware_dfu" || return $?
    else
        echo "${script_name}: Device must be in DFU mode to flash" >&2
        return 1
    fi
}

clean-up ()
{
    local firmware_bin=$1
    local firmware_dfu=$2

    $RM_CMD -f "$firmware_bin" "$firmware_dfu" || return $?
}

if test ."$0" = ."${BASH_SOURCE[0]}"; then
    declare script=''
    declare script_name=''

    script=$(resolve-existing "$0") || exit $?
    script_name=${script##*/}

    declare default_firmware_elf=''

    default_firmware_elf=$($LS_CMD *.elf) || exit $?

    declare firmware_elf=${1:-"$default_firmware_elf"}

    if test ! -f "$firmware_elf"; then
        usage "${script_name}: ${firmware_elf}: No such file or directory"
        exit 1
    elif ! validate-elf "$firmware_elf"; then
        usage "${script_name}: ${firmware_elf}: Expected ELF executable"
        exit 2
    fi

    declare firmware_bin=''
    declare firmware_dfu=''

    firmware_bin=$(generate-bin "$firmware_elf") || exit $?
    firmware_dfu=$(generate-dfu "$firmware_bin") || exit $?
    flash-dfu "$firmware_dfu" || exit $?
    clean-up "$firmware_bin" "$firmware_dfu" || exit $?
fi
