#!/usr/bin/env bash
#
# @(#) stlink-flash-elf
#
# This script flashes ELF firmware to an STM32 device over USB in
# ST-Link Mode.
#
: ${FILE_CMD:='/usr/bin/file'}
: ${ARM_NONE_OBJCOPY_CMD:='/usr/bin/arm-none-eabi-objcopy'}
: ${ST_FLASH_CMD:='/usr/bin/st-flash'}

: ${TEXT_ADDRESS:='0x08000000'}

validate-elf ()
{
    local firmware_elf=$1

    local status=''

    case $($FILE_CMD "$firmware_elf") in
        *'ELF 32-bit LSB'*) status=0 ;;
        *) status=1 ;;
    esac

    return $status
}

generate-bin ()
{
    local firmware_elf=$1

    local firmware_bin=${firmware_elf%.elf}.bin

    $ARM_NONE_OBJCOPY_CMD -O binary "$firmware_elf" "$firmware_bin" || return $?
    echo "$firmware_bin"
}

stlink-flash-firmware ()
{
    local firmware_bin=$1

    $ST_FLASH_CMD write "$firmware_bin" "$TEXT_ADDRESS" || return $?
}

if test ."$0" = ."${BASH_SOURCE[0]}"; then
    declare script_name=${0##*/}
    declare firmware_elf=$1

    if (( $# == 0 )); then
        echo "Usage: ${script_name} ELF-FIRMWARE" >&2
    elif test ! -f "$firmware_elf"; then
        echo "${script_name}: ${firmware_elf}: No such file or directory" >&2
        echo "Usage: ${script_name} ELF-FILE" >&2
        exit 1
    elif ! validate-elf "$firmware_elf"; then
        echo "${script_name}: ${firmware_elf}: Expected ELF executable" >&2
        echo "Usage: ${script_name} ELF-FIRMWARE" >&2
        exit 2
    fi

    declare firmware_bin=''

    firmware_bin=$(generate-bin "$firmware_elf") || exit $?
    stlink-flash-firmware "$firmware_bin" || exit $?
fi
